export const reducerCases = {
    SET_SEARCH: 'SET_SEARCH',
    SET_ANIME_LIST: 'SET_ANIME_LIST',
    SET_DETAIL: 'SET_DETAIL',
    SET_RECOMMEND: 'SET_RECOMMEND',
    SET_HISTORY_ID: 'SET_HISTORY_ID',
    SET_SCHEDULE: 'SET_SCHEDULE',
    SET_TOP_POPULOR: 'SET_TOP_POPULOR',
    SET_TOP_FAVOURITE: 'SET_TOP_FAVOURITE',
    SET_TOP_AIRING: 'SET_TOP_AIRING',
    SET_FIRST_LOAD_HOME: 'SET_FIRST_LOAD_HOME',
    
    RESET_ANIME_LIST: 'RESET_ANIME_LIST',
    RESET_DETAIL: 'RESET_DETAIL',
    RESET_RECOMMEND: 'RESET_RECOMMEND',
}