export const reducerCases = {
    SET_SEARCH: 'SET_SEARCH',
    SET_ANIME_LIST: 'SET_ANIME_LIST',
    SET_PAGE: 'SET_PAGE',
    SET_DETAIL: 'SET_DETAIL',
    SET_RECOMMEND: 'SET_RECOMMEND',
    SET_HISTORY_ID: 'SET_HISTORY_ID',
    TOP_POPULOR: 'TOP_POPULOR',
    TOP_FAVOURITE: 'TOP_FAVOURITE',
    SET_TOP_AIRING: 'SET_TOP_AIRING',
    
    RESET_ANIME_LIST: 'RESET_ANIME_LIST',
    RESET_DETAIL: 'RESET_DETAIL',
    RESET_RECOMMEND: 'RESET_RECOMMEND',
}