export const reducerCases = {
    SET_SEARCH: 'SET_SEARCH',
    SET_ANIME_LIST: 'SET_ANIME_LIST',
    SET_PAGE: 'SET_PAGE',
    SET_DETAIL: 'SET_DETAIL',
    SET_RECOMMEND: 'SET_RECOMMEND',
    SET_HISTORY_ID: 'SET_HISTORY_ID',
    
    RESET_DETAIL: 'RESET_DETAIL',
    RESET_RECOMMEND: 'RESET_RECOMMEND',
}